name: class12 Terraform apply on Dev

on:
  push:
    branches:
      - main
    paths:
      - class12/infra/**
  workflow_dispatch:

jobs:
  terraform-dev-apply:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
      TERRAFORM_VER: 1.8.1
      TERRAFORM_PATH: class12/infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VER }}

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform init -backend-config=vars/dev.tfbackend

      # - name: Terraform Plan
      #   working-directory: ${{ env.TERRAFORM_PATH }}
      #   run: terraform plan -var-file=vars/dev.tfvars 

      # - name: Terraform Apply
      #   working-directory: ${{ env.TERRAFORM_PATH }}
      #   run: terraform apply -var-file=vars/dev.tfvars -auto-approve

      - name: Terraform Destroy
      working-directory: ${{ env.TERRAFORM_PATH }}
      run: terraform destroy -var-file=vars/dev.tfvars -auto-approve