name: class12 Terraform apply on Prod

on:
 ## Uncomment the following lines to trigger on push to main branch and specific paths
  # push:
  #   tags:
  #     - 'v*.*.*'  # Matches version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:
env:
  ENVIRONMENT: prod

jobs:
  terraform-dev-apply:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
      TERRAFORM_VER: 1.8.1
      TERRAFORM_PATH: class12/infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VER }}

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform init -backend-config=vars/${{ env.ENVIRONMENT }}.tfbackend

      # if only running plan
      # - name: Terraform Plan
      #   working-directory: ${{ env.TERRAFORM_PATH }}
      #   run: terraform plan -var-file=vars/${{ env.ENVIRONMENT }}.tfvars 

      ### Uncomment the following lines to apply the Terraform configuration ###
      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform apply -var-file=vars/${{ env.ENVIRONMENT }}.tfvars -auto-approve

      ### Uncomment the following lines to destroy the Terraform configuration ###
      # - name: Terraform Destroy
      #   working-directory: ${{ env.TERRAFORM_PATH }}
      #   run: terraform destroy -var-file=vars/${{ env.ENVIRONMENT }}.tfvars -auto-approve